### ISSUE TITLE
Why RedisClient is incomplete ?

### ISSUE THREAD

**Issue by Garfield028** [NServiceKit/NServiceKit#25]
hi,

I liked to use the "RemoveByPattern" method RedisClient class.
Unfortunately, it is not avaialble.
Do you intend to update the class soon?

Thank you.

**Comment by vdaron** [comment]
Hi,

Could you give me some more info ? http://redis.io/commands

Tks

Vincent.

**Comment by Garfield028** [comment]
I have stored in "Redis" more keys with the same beginning.
ex: "FavoriteMenu:UserId98" and "FavoriteMenu:UserId103"

It is possible that I have to invalidate(delete) the cache of all keys that start with "FavoriteMenu."

The method "RemoveByPattern" allows me to pass it as parameter "FavoriteMenu*"

This method is present in ServiceStack.Redis but not NServiceKit.Redis.

tks

Xavier

**Comment by vdaron** [comment]
Please do not cross post issues.

I've answer on the NServiceKit.Redis project
